[tool.poetry]
name = "Nene"
version = "2.0.0"
description = "跨适配器的通用全功能机器人"
authors = ["Agnes Digital <Z735803792@163.com>"]
license = "AGPL"
readme = "README.md"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
secondary = true

[[tool.poetry.source]]
name = 'aliyun'
url = 'https://mirrors.aliyun.com/pypi/simple/'
secondary = true

[[tool.poetry.source]]
name = 'pypi_'
url = 'https://pypi.python.org/simple'
secondary = true

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    {name = "开黑啦", module_name = "nonebot.adapters.kaiheila"},
    {name = "QQ 频道", module_name = "nonebot.adapters.qqguild"},
    {name = "OneBot V12", module_name = "nonebot.adapters.onebot.v12"}
]
plugins = ["nonebot_plugin_apscheduler",
"nonebot_plugin_userinfo",
"nonebot-plugin-send-anything-anywhere"]
plugin_dirs = ["src/plugins"]