[tool.poetry]
name = "Nene"
version = "2.0.0"
description = "跨适配器的通用全功能机器人"
authors = ["Agnes Digital <Z735803792@163.com>"]
license = "AGPL"
readme = "README.md"

[[tool.poetry.source]]
name = "tencentyun"
url = "https://mirrors.tencent.com/pypi/simple"
secondary = true

[[tool.poetry.source]]
name = 'aliyun'
url = 'https://mirrors.aliyun.com/pypi/simple/'
secondary = true

[[tool.poetry.source]]
name = 'pypi_'
url = 'https://pypi.python.org/simple'
secondary = true

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    {name = "开黑啦", module_name = "nonebot.adapters.kaiheila"},
    {name = "QQ 频道", module_name = "nonebot.adapters.qqguild"},
    {name = "OneBot V12", module_name = "nonebot.adapters.onebot.v12"}
]
plugins = ["nonebot_plugin_apscheduler",
"nonebot_plugin_userinfo",
"nonebot-plugin-send-anything-anywhere"]
plugin_dirs = ["src/plugins"]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0"
nonebot-adapter-qqguild = "^0.2.3"
nonebot-adapter-kaiheila = "^0.2.7"
nonebot-adapter-onebot = "^2.2.3"
nonebot-plugin-apscheduler = "^0.3.0"
nonebot-plugin-send-anything-anywhere = "^0.2.7"
nonebot_plugin_userinfo = "0.0.2"
pillow = "^9.0.0"
httpx = "^0.24.0"
aiofiles = "^23.1.0"